
spring:
  application:
    name: bookings
  config:
    import: "configserver:${SPRING_CONFIG_URI:http://localhost:8888}"
    discovery:
      enabled: true
    fail-fast: false
    retry:
      initial-interval: 2000
      max-attempts: 5
      multiplier: 1.5
