
spring:
  application:
    name: gateway
  cloud:
    config:
      name: stylists,bookings,gateway
  config:
    import: "configserver:${SPRING_CONFIG_URI:http://localhost:8888}"
    fail-fast: true
    retry:
      initial-interval: 2000
      max-attempts: 5
      multiplier: 1.5
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.properties.bind: DEBUG
